spring.application.name=library-backend
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://nishwanth2003_db_user:Fp6UcDC5bCdkGBCm@cluster0.q1hkyu9.mongodb.net/library_db?appName=Cluster0

# Error Handling
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

